spring:
  data:
    mongodb:
      uri: mongodb://root:rootpassword@mongo:27017/userdb?authSource=admin
  application:
    name: user-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
server:
  port: 8082
